import os

# Direct access
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY","ENTER_YOUR_API_KEY")
MIXTRAL_API_KEY = os.getenv("MIXTRAL_API_KEY",'ENTER_YOUR_API_KEY')
MIXTRAL_API_URL = os.getenv("MIXTRAL_API_URL","ENTER_YOUR_URL")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY","ENTER_YOUR_API_KEY")
